feat: added login
SakaRicky/SchoolX pull request #13
Opened 2021-10-23 21:50 UTC by SakaRicky

2021-10-25 21:25 UTC, lkuz requested changes

2021-10-25 21:25 UTC, lkuz commented on pages/teacher_registration.tsx
>  import FlashNotification from "components/FlashNotification";
sum the components imports

`import { AddTecherForm, FlashNotification }  from 'components';`

And avoid using default exports - you can read about the benefits of named imports/exports here: [Why you should avoid default imports/exports](https://basarat.gitbook.io/typescript/main-1/defaultisbad)

2021-10-25 21:25 UTC, lkuz commented on components/FormUi/Button/index.tsx
>      children: React.ReactChild | React.ReactChildren;
1. No need to access ReactChild and ReactChildren from React.XY - just ReactChild or ReactChildren
2. You could just use ReactNode instead of those two separate types. Depending on how specific the prop type has to be. In most cases ReactNode should be fine.

[You can read about it here](https://www.carlrippon.com/react-children-with-typescript/)

2021-10-25 21:25 UTC, lkuz commented on components/FormUi/CheckBox/index.tsx
> +import * as React from "react";
remove React import and avoid using * imports

2021-10-25 21:25 UTC, lkuz commented on components/FormUi/CheckBox/index.tsx
> +    const configCheckBoxGroup: any = {
no explicit any type - never use any. Try to get the type somewhere from or build your own.
You could also use unknown instead of any.

[Source to read](https://43081j.com/2019/02/typescript-avoid-using-any)

2021-10-25 21:25 UTC, lkuz commented on components/FormUi/TextFields/index.tsx
>      const configTextField: any = {
no implicit any

2021-10-25 21:25 UTC, lkuz commented on components/Login/index.tsx
> +import * as React from 'react';
remove react import

2021-10-25 21:25 UTC, lkuz commented on components/Login/index.tsx
> +import CheckBoxWrapper from 'components/FormUi/CheckBox';
sum imports

2021-10-25 21:25 UTC, lkuz commented on components/Login/index.tsx
> +import * as yup from 'yup';
you could even deconstruct the yup import and only import the functions you need from it instead of importing everything from it. But this is fine in this case. Just you know about it.

2021-10-25 21:25 UTC, lkuz commented on components/Login/index.tsx
> +      } catch (error: any) {
Type the error. I guess it's a string or boolean?

2021-10-25 21:31 UTC, SakaRicky commented on pages/teacher_registration.tsx
>  import FlashNotification from "components/FlashNotification";
Ok

2021-10-25 22:40 UTC, SakaRicky commented on components/Login/index.tsx
> +      } catch (error: any) {
I read type of catch can only be "any" or "unknown" and "unknown" can't be logged, so any is a walk around

2021-10-28 10:56 UTC, lkuz approved these changes

2021-10-28 11:18 UTC, merged