feat: created the view for the class list
SakaRicky/SchoolX pull request #16
Opened 2021-10-25 19:44 UTC by SakaRicky

2021-10-25 21:50 UTC, lkuz requested changes

2021-10-25 21:50 UTC, lkuz commented on components/ClassList/index.tsx
> +import React from 'react';
remove react import

2021-10-25 21:50 UTC, lkuz commented on components/ClassList/index.tsx
> +  id: 'number' | 'id' | 'first_name' | 'last_name' | 'date_of_birth' | 'gender' | 'fathers_name' | 'fathers_phone';
Did you mean to use the `number` type here instead of 'number' as a string?
The same for the 'id'.
I mean, what is the benefit from having elements with the id: "id"

2021-10-25 21:50 UTC, lkuz commented on pages/class_list.tsx
> +            } catch (error: any) {
No implicit any

2021-10-25 21:50 UTC, lkuz commented on services/classList.ts
> +const baseURL = 'http://localhost:5000/';
This should be defined in an environment variable.

You could write something like this:
`const baseURL = process.env.HOST || 'http://localhost:5000/'`

As we want to deploy it to a server later on, this makes it easy to switch between hosts.

2021-10-25 21:50 UTC, lkuz commented on types.ts
>      message: string | any,
no implicit any

2021-10-25 23:17 UTC, SakaRicky commented on components/ClassList/index.tsx
> +  id: 'number' | 'id' | 'first_name' | 'last_name' | 'date_of_birth' | 'gender' | 'fathers_name' | 'fathers_phone';
number string to display in a column in the table. Since the list is shown alphabetically, number is is sort of index.
For id I will use it for matricule later, now I don't have matricule but id serves as a placeholder to be later replaced by matricule.

2021-10-28 10:57 UTC, lkuz submitted a review, later dismissed

2021-10-28 12:08 UTC, lkuz approved these changes

2021-10-28 12:08 UTC, merged